desafio/desafio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('funcionarios.urls')),
]

desafio/funcionarios/urls.py
from django.contrib import admin
from django.urls import path
from funcionarios.views import index, delete_funcionario, create, edit_funcionario

app_name = 'funcionarios'

urlpatterns = [
    path('', index, name='index'),
    path('funcionario/create/', create, name='create'),
    path('funcionario/edit/<int:funcionario_id>/', edit_funcionario, name='edit'),
    path('funcionario/delete/<int:funcionario_id>/', delete_funcionario, name='delete'),
]

desafio/funcionarios/models.py
from django.db import models

# Create your models here.
class Funcionario(models.Model):
    name = models.CharField(max_length=64)
    phone = models.CharField(max_length=15)
    email = models.EmailField()
    city = models.CharField(max_length=32)
    
    def __str__(self):
        return self.name

desafio/funcionarios/forms.py
from django.forms import ModelForm, TextInput, ValidationError
from funcionarios.models import Funcionario

class FuncionariosForm(ModelForm):
    class Meta:
        model = Funcionario
        fields = ['name', 'phone', 'email', 'city']
        widgets = {'phone': TextInput(attrs={'inputmode': 'numeric'}),}
        
    
    def clean_name(self):
        name = self.cleaned_data['name']
        if len(name) < 3:
            raise ValidationError('O campo deve ter pelo menos 3 caractes')
        return name
    
    def clean_phone(self):
        phone = self.cleaned_data['phone']
        errors = []
            
        if phone[0] != '(': 
            if not errors: errors.append('Digite apenas números')
        if phone[3] != ')':
            if not errors: errors.append('Digite apenas números')
        if not phone[1:3].isdigit():
             if not errors: errors.append('Digite apenas números')
        if phone[10] != '-':
            if not errors: errors.append('Digite apenas números')
        if not phone[5:10].isdigit():
            if not errors: errors.append('Digite apenas números')
        if not phone[11:15].isdigit():   
            if not errors: errors.append('Digite apenas números')
            
        if len(phone) != 15:
            errors.append('O telefone digitado está incorreto')
        
        
        if errors:
            raise ValidationError(errors)
        
        return phone
        
        
        

desafio/funcionarios/views.py
from django.shortcuts import render, redirect, get_object_or_404
from funcionarios.models import Funcionario
from funcionarios.forms import FuncionariosForm

# Create your views here.
def index(request):
    funcionarios = Funcionario.objects.all()
    context = {
        'funcionarios_list': funcionarios,
        'page_title': 'Página Inicial'
    }
    return render(request, 'funcionarios/pages/index.html', context=context)


def create(request):
    if request.method == 'POST':
        form = FuncionariosForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('funcionarios:index')
    else:
        form = FuncionariosForm()
    
    context = {
        'form': form,
        'page_title': 'Cadastrar novo funcionário'
    }
    return render(request, 'funcionarios/pages/form.html', context=context)


def edit_funcionario(request, funcionario_id):
    funcionario = get_object_or_404(Funcionario, id=funcionario_id)

    if request.method == 'POST':
        form = FuncionariosForm(request.POST, instance=funcionario)
        if form.is_valid():
            form.save()
            return redirect('funcionarios:index')
    
    else:
        form = FuncionariosForm(instance=funcionario)
        
    context = {
        'form': form,
        'page_title': f'Editando {funcionario.name}'
    }
    return render(request, 'funcionarios/pages/form.html', context=context)


def delete_funcionario(request, funcionario_id):
    funcionario = get_object_or_404(Funcionario, id=funcionario_id)
    funcionario.delete()
    
    return redirect('funcionarios:index')

desafio/funcionarios/templates/funcionarios/pages/form.html
{% load static %}
{% include "funcionarios/partials/head.html" %}

</head>
<body>

    <div class="container">
        <h1>Cadastrar Funcionário</h1>

        <form action="#" method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class='form-field'>
                    {{field.label_tag}}
                    {{ field }}

                    {% for error in field.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
            {% endfor %}

            <input type="submit" value="Cadastrar">
        </form>
    </div>

    <script src="https://unpkg.com/imask"></script>
    <script src="{% static "funcionarios/javascript/phone_mask.js" %}"></script>
</body>
</html>

desafio/funcionarios/templates/funcionarios/pages/index.html
{% include "funcionarios/partials/head.html" %}
</head> 
<body>

  <div class="container">
    <h1>Funcionários</h1>
    <a class="add-button" href="{% url "funcionarios:create" %}"> <i class="fa-solid fa-plus"></i> Adicionar Funcionário</a>
    <div class="table-container">
      <table>
        <thead>
          <tr>
            <th>Nome</th>
            <th>Telefone</th>
            <th>Email</th>
            <th>Cidade</th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody>
          {% for funcionario in funcionarios_list %}
            {% include "funcionarios/partials/funcionario_row.html" %}       
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

</body>
</html>

desafio/funcionarios/templates/funcionarios/partials/funcionario_row.html
<tr>
    <td>{{ funcionario.name }}</td>
    <td>{{ funcionario.phone }}</td>
    <td>{{ funcionario.email }}</td>
    <td>{{ funcionario.city }}</td>
    <td>
        <div class="actions">
            {% comment %} <a href="{% url "funcionarios:edit" funcionario.id %}" class="edit-button" ><i class="fa-solid fa-pen"></i></a> {% endcomment %}
            <a href="{% url "funcionarios:edit" funcionario.id %}" class="edit-button" ><i class="fa-solid fa-pen-to-square"></i></a>
            <a href="{% url "funcionarios:delete" funcionario.id %}" class="delete-button" ><i class="fa-solid fa-trash-can"></i></a>
        </div>
    </td>
</tr>

desafio/funcionarios/templates/funcionarios/partials/head.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ page_title }}</title>
    <script src="https://kit.fontawesome.com/1c1371ef50.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static "funcionarios/css/style.css" %}">
    <link rel="shortcut icon" href="{% static "funcionarios/images/favicon.ico" %}" type="image/x-icon">    